# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "打development包"
  lane :development do |options|
    clear_derived_data(derived_data_path: "./DerivedData") # 清除本地编译缓存
    match(type: "development", force_for_new_devices: false, readonly: true) # fastlane match 管理证书
    gym(scheme: "FastlaneDemo",
      workspace: "FastlaneDemo.xcworkspace",
      configuration: "Debug",
      export_method: "development",#打包的类型
      output_directory: "./build",#生成的ipa路径
      output_name: "FastlaneDemo.ipa",#生成的ipa文件名
      silent: false,
      include_symbols: true,# 是否包含符号表
      derived_data_path: "./DerivedData",
      # clean:true,
      xcargs: "-UseNewBuildSystem=NO"
  )
  end
end
